// src/grudge/skills/base.ts
//
// Phase 5-prep stub. Mirrors `Skill.cs` + `ScriptableSkill.cs` from the Unity
// tree. The typed subclasses (`DamageSkill`, `HealSkill`, `BuffSkill`, etc.)
// land in Phase 5 alongside the Unity `ScriptableSkills/*.cs` ports.
import type { AttributeKey } from "../attributes";

export type SkillKind =
  | "active"
  | "passive"
  | "ultimate";

export type SkillEffectKind =
  | "damage" | "heal" | "buff" | "debuff" | "projectile" | "area"
  | "transformation";

/** The frozen, ScriptableObject-shaped data definition. Resolved at boot
 *  from `src/grudge/data/skills/<id>.json` (generated by
 *  `scripts/import-grudge-data.mjs` parsing Unity .asset YAML). */
export interface SkillDef {
  id: string;
  name: string;
  icon: string;
  kind: SkillKind;
  /** "dmg" | "aoe" | "cc" | "cd" | "passive" | "ult" — feeds the HUD's
   *  `.tt-tag` chip styles in UIlayer.html / mainpanel.html. */
  tags: string[];
  /** Stamina/Mana/Health cost. Plain string for the tooltip ("35 SP", "—"). */
  cost: string;
  /** Cooldown text for the tooltip. */
  cd: string;
  cdSeconds: number;
  description: string;
  effect: SkillEffectKind;
  /** Skill power scales primarily with this attribute. */
  scalingAttribute: AttributeKey;
  scalingFactor: number;
}

/** Read-only catalog returned by `loadSkills(json)` (Phase 5). */
export type SkillCatalog = Readonly<Record<string, Readonly<SkillDef>>>;

/** Frozen empty catalog the HUD falls back to before Phase 5 lands. */
export const EMPTY_SKILL_CATALOG: SkillCatalog = Object.freeze({});

export class UnimplementedSkillError extends Error {
  constructor(slot: string) {
    super(`[grudge/skills] '${slot}' not implemented yet — Phase 5 port pending.`);
    this.name = "UnimplementedSkillError";
  }
}

/** A skill cast envelope produced by the player skill bar. The world owns
 *  the actual hit-resolution; we only describe what was attempted. */
export interface SkillCast {
  skillId: string;
  casterId: string;
  /** Optional; melee abilities resolve against the auto-target in front. */
  targetId?: string;
  /** Wall-clock ms when the cast was queued. */
  queuedAt: number;
}
